package io.parrot.processor;

public enum ParrotHeaderType {

    PARROT_SOURCE_NAME, PARROT_META, PARROT_CHANGE_EVENT_KEY, PARROT_CHANGE_EVENT_VALUE, PARROT_SINK_TARGET_ENDPOINT, PARROT_IS_VALID, PARROT_DATA;

}