site_name: Parrot Stream
pages:
    - Introduction: index.md
    - Quickstart: quickstart.md
    - Development: development.md
    - Installation & Configuration:
        - 'Overview': 'installation/overview.md'
        - 'Cloudera CSDs': 'installation/cloudera-csds.md'
        - 'Dockers': 'installation/dockers.md'
    - Connectors:
        - 'HBase Connector': 'connectors/hbase-connector.md'
        - 'Kudu Connector': 'connectors/kudu-connector.md'
    - FAQ: faq.md
theme: readthedocs
repo_url: https://github.com/parrot-stream/parrot
edit_uri: edit/master/docs
site_author: Matteo Capitanio
