/**
 * Enables LogMiner 
 */
SHUTDOWN IMMEDIATE;
STARTUP MOUNT;
ALTER DATABASE ARCHIVELOG;
ALTER DATABASE OPEN;

/**
 * Enables Supplemental Logging 
 */
ALTER SESSION SET CONTAINER=CDB$ROOT;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (PRIMARY KEY) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER SYSTEM SWITCH LOGFILE;

/**
 * Creates the parrot user 
 */
ALTER session SET "_ORACLE_SCRIPT"=true;
CREATE USER parrot IDENTIFIED BY parrot CONTAINER=all;
GRANT ALL PRIVILEGES TO parrot CONTAINER=all;