version: '3'
services:
  debezium:
    image: mcapitanio/debezium:0.5.1
    networks:
    - parrot
    external_links:
    - postgres
    ports:
    - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: parrot.debezium.configs
      OFFSET_STORAGE_TOPIC: parrot.debezium.offsets
      BOOTSTRAP_SERVERS: kafka:9092
      LOG_LEVEL: INFO
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge