version: "2"

services:
                  
    debezium:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/debezium:0.5
        networks:
            - parrot
        volumes:
            - debezium_logs:/kafka/logs
            - debezium_conf:/kafka/conf
        ports:
            - "8083:8083"
        environment:
            - GROUP_ID=1
            - CONFIG_STORAGE_TOPIC=parrot.debezium.configs
            - OFFSET_STORAGE_TOPIC=parrot.debezium.offsets
            - BOOTSTRAP_SERVERS=kafka:9092

volumes:
    debezium_logs:
    debezium_conf:

networks:
    default:
      external:
        name: parrot
    parrot:
        driver: bridge
