version: "2"

services:

    postgres:
        extends:
            file: postgres.yml
            service: postgres

    parrot:
        build:
            context: ..
            dockerfile: Dockerfile
        image: ${DOCKER_IMAGE}:${DOCKER_TAG}
        networks:
            - parrot
        links:
            - postgres
        ports:
            - "80${ID}:8080"
            - "99${ID}:9990"
            - "87${ID}:8787"
        privileged: true
        environment:
            - DB_HOSTNAME=postgres
            - DB_NAME=parrot
            - DB_DATASOURCE=ParrotDS
            - KAFKA_BROKER_HOSTNAME=kafka
            - DEBEZIUM_HOSTNAME=debezium
            - LOCAL_UNIT=${LOCAL_UNIT}
            - LOCAL_INTEGRATION=${LOCAL_INTEGRATION}
            - PIPELINE_UNIT=${PIPELINE_UNIT}
            - PIPELINE_INTEGRATION=${PIPELINE_INTEGRATION}
            - DEVELOPMENT=${DEVELOPMENT}
            - DEBUG=${DEBUG}

volumes:
    postgres_data:
    wiremock_files:
    wiremock_mappings:

networks:
    default:
      external:
        name: parrot
    parrot:
        driver: bridge