version: '3'
services:
  hadoop:
    image: parrotstream/hadoop:latest
    networks:
    - parrot
    external_links:
    - zookeeper
    volumes:
    - hadoop_conf:/etc/hadoop/conf
    ports:
    - 50070:50070
    - 50075:50075
    - 8020:8020
    - 8042:8042
    - 8088:8088
    - 8188:8188
    - 19888:19888
volumes:
  hadoop_conf:
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge