version: '3'
services:
  impala:
    image: parrotstream/impala-kudu:latest
    privileged: true
    external_links:
    - hive
    networks:
    - parrot
    ports:
    - 21000:21000
    - 21050:21050
    - 25000:25000
    - 25010:25010
    - 25020:25020
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge