version: '3'
services:
  impala:
    image: parrotstream/impala:latest
    external_links:
    - hive
    - hadoop
    - hbase
    networks:
     - parrot
    ports:
    - 21000:21000
    - 21050:21050
    - 25000:25000
    - 25010:25010
    - 25020:25020
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge