version: '3'
services:
  impala:
    image: mcapitanio/impala:2.8.0-cdh5.11.1
    external_links:
    - hive
    - hadoop
    - hbase
    networks:
     - parrot
#        aliases:
#        - hadoop
#    volumes:
#    - hadoop_conf:/etc/hadoop/conf
    ports:
    - 21000:21000
    - 21050:21050
    - 25000:25000
    - 25010:25010
    - 25020:25020
#    - 50070:50070
#    - 50075:50075
#    - 8020:8020
#    - 8042:8042
#    - 8088:8088
#    - 8188:8188
#    - 19888:19888
#volumes:
#  hadoop_conf:
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge