version: '3'
services:
  kafka-connect-ui:
    image: mcapitanio/kafka-schema-registry-ui:0.9.1
    networks:
    - parrot
    ports:
    - 9002:8000
    environment:
      SCHEMAREGISTRY_URL: http://kafka:8082
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge