version: '3'
services:
  kafka-connect-ui:
    image: mcapitanio/kafka-connect-ui:0.9.2
    networks:
    - parrot
    external_links:
    - impala-kudu-master
    ports:
    - 9001:8000
    environment:
      CONNECT_URL: http://kafka-connect:8083
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge