version: '3'
services:
  kafka:
    image: mcapitanio/kafka:0.10.2.0
    networks:
    - parrot
    external_links:
    - zookeeper
    ports:
    - 9092:9092
    - 8081:8081
    - 8082:8082
    - 8084:8083
    - 8001:8000
    environment:
    - KAFKA_REST_PROXY_URL=http://localhost:8082
    - PROXY=true
    - PROXY_SKIP_VERIFY=true
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge