version: "2"

services:

    zookeeper:
        extends:
            file: zookeeper.yml
            service: zookeeper
           
    kafka:
        image: mcapitanio/kafka:0.10.2.0
        networks:
            - parrot
        links:
            - zookeeper
        volumes:
            - kafka_conf:/opt/kafka/config
            - kafka_logs:/opt/kafka/logs
            - kafka_manager_conf:/opt/kafka-manager/conf
            - kafka_manager_logs:/opt/kafka-manager/logs
        ports:
            - "9092:9092"
            - "9000:9000"
            - "8081:8081"
            - "8082:8082"
            - "8000:8000"
        environment:
            - KAFKA_REST_PROXY_URL=http://localhost:8082
            - PROXY=true
            - PROXY_SKIP_VERIFY=true

volumes:
    kafka_conf:
    kafka_logs:
    kafka_manager_conf:
    kafka_manager_logs:
    zookeeper_data:
    zookeeper_logs:
    zookeeper_conf:

networks:
    default:
      external:
        name: parrot
    parrot:
        driver: bridge
