version: '3'
services:
  kafka:
    image: parrotcdc/kafka:0.10.2.0
    networks:
    - parrot
    external_links:
    - zookeeper
    ports:
    - 9092:9092
    - 8082:8082
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge