version: '3'
services:
  kafka-topics-ui:
    image: parrotcdc/kafka-topics-ui:0.9.2
    networks:
    - parrot
    external_links:
    - kafka
    ports:
    - $KAFKA_TOPICS_UI_PORT:$KAFKA_TOPICS_UI_PORT
    environment:
      KAFKA_REST_PROXY_URL: http://kafka:8082
      PROXY: "true"
      KAFKA_TOPICS_UI_PORT: $KAFKA_TOPICS_UI_PORT
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge