version: '3'
services:
  kafka-connect-ui:
    image: parrotstream/kafka-connect-ui:0.9.2
    networks:
    - parrot
    external_links:
    - parrot
    ports:
    - $KAFKA_CONNECT_UI_PORT:$KAFKA_CONNECT_UI_PORT
    environment:
      CONNECT_URL: http://parrot:8083
      PROXY: "true"
      KAFKA_CONNECT_UI_PORT: $KAFKA_CONNECT_UI_PORT
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge