version: '3'
services:
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile
    image: mcapitanio/mongodb:latest
    networks:
    - parrot
    ports:
    - 27017:27017
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge