version: "2"

services:

    mongodb:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/mongodb:latest
        networks:
            - parrot
        volumes:
            - mongodb_parrot_data:/data/db
        ports:
            - "27017:27017"

volumes:
    mongodb_parrot_data:

networks:
    default:
      external:
        name: parrot
    parrot:
        driver: bridge