version: '3'
services:
  mysql:
    image: library/mysql:8
    networks:
    - parrot
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: parrot
      MYSQL_DATABASE: parrot
    privileged: true
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge