version: '3'
services:
  parrot:
    build:
      context: ..
      dockerfile: Dockerfile
    image: ${DOCKER_IMAGE}:${DOCKER_TAG}
    networks:
    - parrot
    external_links:
    - kafka
    - zookeeper
    - impala
    - kudu
    ports:
    - $PARROT_PORT:$PARROT_PORT
    - $SCHEMA_REGISTRY_PORT:$SCHEMA_REGISTRY_PORT
    privileged: true
    environment:
      DB_NAME: parrot
      POSTGRESQL_HOSTNAME: postgres
      MYSQL_HOSTNAME: mysql
      MONGODB_HOSTNAME: mongodb
      ORACLE_HOSTNAME: oracle
      KAFKA_BROKER_HOSTNAME: kafka
      BOOTSTRAP_SERVERS: kafka:9092
      GROUP_ID: parrot
      SCHEMA_REGISTRY_PORT: $SCHEMA_REGISTRY_PORT
      LISTENERS: http://0.0.0.0:$SCHEMA_REGISTRY_PORT
      PARROT_PORT: $PARROT_PORT
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge