version: '3'
services:
  postgres:
    image: mcapitanio/postgres:9.6
    networks:
    - parrot
    ports:
    - 5432:5432
    volumes:
    - ./sources/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres
    privileged: true
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge