version: "2"

services:

    postgres:
        image: mcapitanio/postgres:9.6
        networks:
            - parrot
        ports:
            - "5432:5432"
        volumes:
            - postgres_parrot_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
        privileged: true

volumes:
    postgres_parrot_data:
    
networks:
    default:
      external:
        name: parrot
    parrot:
        driver: bridge
