version: "2"

services:
           
    streamsets:
        build:
            context: .
            dockerfile: Dockerfile
        image: mcapitanio/streamsets:2.4.1.0
        networks:
            - parrot
        volumes:
            - streamsets_stagelibs:/opt/streamsets-datacollector/streamsets-libs
            - streamsets_stagelibs_extras:/opt/streamsets-datacollector-extras
            - streamsets_data:/data
            - streamsets_conf:/etc/sdc
        ports:
            - "18630:18630"
        extra_hosts:
            - "cdpco02.cdpsede.cassaddpp.it:10.100.11.27"
            - "cdpco04.cdpsede.cassaddpp.it:10.100.11.29"
            

volumes:
    streamsets_stagelibs:
    streamsets_stagelibs_extras:
    streamsets_data:
    streamsets_conf:

networks:
    default:
      external:
        name: parrot
    parrot:
        driver: bridge