version: '3'
services:
  zookeeper:
    image: parrotstream/zookeeper:latest
    ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
    - 8080:8080
    networks:
    - parrot
networks:
  default:
    external:
      name: parrot
  parrot:
    driver: bridge